name: Dockerise Python App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python (optional — useful if you want pre-checks)
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t helloworld-app .

    # Step 4: Run container to test
    - name: Run Docker container
      run: |
        docker run --name helloworld-test -d helloworld-app
        sleep 5  # wait for container to start
        docker ps -a  # list containers
        docker logs helloworld-test  # show app output

    # Step 5: Clean up
    - name: Stop and remove container
      run: |
        docker stop helloworld-test
        docker rm helloworld-test
